[project]
name = "pycrypt-lib"
version = "1.0.2"
description = "A pure Python implementation of cryptographic primitives, written in a clean, Pythonic, and type-safe way."
readme = "README.md"
authors = [
    { name = "Aravindaksha Balaji", email = "aravindakshabalaji@gmail.com" },
    { name = "Arnav Guntur", email = "arnavguntur.2009@gmail.com" },
]
requires-python = ">=3.9"
dependencies = [
    "egcd>=3.0.0",
    "primefac>=2.0.12",
]

[project.urls]
Homepage = "https://pycrypt-lib.readthedocs.io/en/latest/"
Repository = "https://github.com/WallWarm/pycrypt"
Issues = "https://github.com/WallWarm/pycrypt/issues"

[tool.uv.build-backend]
module-name = "pycrypt"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.basedpyright]
typeCheckingMode = "recommended"
ignore = [
    "tests/*.py"
]

[tool.ruff]
exclude = [
    "tests/*.py"
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
	"sphinx>=7.4.7",
    "sphinx-rtd-theme>=3.0.2",
]

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"
